### PR TITLE
Translatable with upload file

### PR DESCRIPTION
**Pull request by atmonshi**
I think this will also fix the issues  with repeater and other components.

this based on https://github.com/filamentphp/filament/pull/11450

~since we hydrating the form directly no need to extract the state for all translatable attributes and set them manually, this should be handled by filament~

fixes: refilling the form with the correct data, tested for upload, hopefully will works the same for other components

### CODE REVIEW

**Comment by Voltra** [comment]
I believe this works with filament curator too

**Comment by atmonshi** [comment]
🎉 thank you, thats amazing news.
will try my best to fix all other issues too :)

**Comment by raiika** [comment]
Is this already fixed on latest 3.3 ?
As I can still replicate it,

1. Create resource with translatable and FileUpload
2. Edit existing resource
3. Change the image
4. Go to other language/locale
5. Click save
6. Go to edit page and one of the language/locale will become error
image

**Comment by atmonshi** [comment]
@raiika please open a new issue and include:

- filament version
- php version
- the plugin version
- are you using [filament version](https://github.com/filamentphp/spatie-laravel-translatable-plugin) of the plugin or [ours](https://github.com/lara-zeus/translatable)?
- share some code so I can reproduce it
- here is our [demo](https://github.com/lara-zeus/translatable-demo) and the upload working fine the cover is translatable:

https://github.com/user-attachments/assets/c1816b21-bb16-4c24-a30a-71db3eb58256

**Comment by raiika** [comment]
before save, change the language/locale first to other language, then click save

**Comment by atmonshi** [comment]
changing the local before save, is a [known bug](https://github.com/lara-zeus/translatable/issues/24)

**Pull request merged**
